# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default
 # vmImage: 'ubuntu-latest'

steps:
# - script: |
#     go get github.com/ezekg/git-hound
#     sudo ln -sf ~/go/bin/git-hound /usr/local/bin/git-hound
#   displayName: 'install git-hound'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      set -euxo pipefail
      git log -p | git hound sniff

    failOnStderr: true