# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  repositories:
  - repository: githound
    type: github
    name: soccerjoshj07/git-hound-config
    endpoint: soccerjoshj07

pool:
 vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: githound

- script: |
    go get github.com/ezekg/git-hound
    sudo ln -sf ~/go/bin/git-hound /usr/local/bin/git-hound
  displayName: 'install git-hound'

- script: | 
    # Write your commands here
    ls -a -R
    echo "git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --staged | git-hound sniff"
    git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --staged | git-hound sniff -config=file	git-hound-config/.githound.yml
  displayName: run git-hound